// <auto-generated />
namespace TAO_CSV_v06.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DailyReads : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DailyReads));
        
        string IMigrationMetadata.Id
        {
            get { return "202104160921256_DailyReads"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
